'use strict';
/*
 * Everything that shells out to the cloudflared binary: one-shot commands, the
 * argv/config.yml for a tunnel process, the account workflow and the binary
 * updater. Nothing here supervises a process -- see runner.js for that.
 */
const fs = require('fs');
const path = require('path');
const { spawn, execFile } = require('child_process');
const {
  APPDEST,
  PKGVAR,
  PKGTMP,
  CF_BIN,
  CF_HOME,
  CF_DIR,
  CERT_FILE,
  TUNNELS_DIR,
  CF_VERSION_FILE,
} = require('./paths');
const { logInfo, logWarn } = require('./log');
const { atomicWrite } = require('./atomic');

/* ------------------------------------------------------- cloudflared runner */

function cfEnv(extra) {
  return Object.assign({}, process.env, {
    HOME: CF_HOME,
    TUNNEL_ORIGIN_CERT: CERT_FILE,
    NO_AUTOUPDATE: 'true',
  }, extra || {});
}

/* Run cloudflared once and collect its output. Never rejects: callers inspect
 * `code`/`error` so a failed command becomes an API error message instead of a
 * crashed request handler. */
function cfExec(args, options) {
  const opts = options || {};
  return new Promise((resolve) => {
    execFile(
      CF_BIN,
      args,
      {
        timeout: opts.timeout || 30000,
        maxBuffer: 8 * 1024 * 1024,
        env: cfEnv(opts.env),
        cwd: opts.cwd || PKGVAR,
      },
      (err, stdout, stderr) => {
        let code = 0;
        if (err) code = typeof err.code === 'number' ? err.code : 1;
        resolve({
          code,
          stdout: stdout || '',
          stderr: stderr || '',
          error: err ? String(err.message || err) : null,
        });
      },
    );
  });
}

let cachedVersion = null;

async function cloudflaredVersion(refresh) {
  if (cachedVersion && !refresh) return cachedVersion;
  if (!fs.existsSync(CF_BIN)) return null;
  const res = await cfExec(['--version'], { timeout: 10000 });
  const text = (res.stdout + ' ' + res.stderr).trim();
  const m = text.match(/cloudflared version ([0-9][^\s]*)/i) || text.match(/^([0-9][^\s]*)/);
  cachedVersion = m ? m[1] : (text || 'unknown');
  return cachedVersion;
}

/* Split a user supplied extra-args string the way a shell would, so a value
 * containing spaces can still be passed as one argument. */
function splitArgs(str) {
  const out = [];
  const re = /"([^"]*)"|'([^']*)'|(\S+)/g;
  let m;
  while ((m = re.exec(String(str || '')))) out.push(m[1] ?? m[2] ?? m[3]);
  return out;
}

function globalArgs(settings) {
  const args = [];
  if (settings.protocol && settings.protocol !== 'auto') args.push('--protocol', settings.protocol);
  if (settings.edgeIpVersion) args.push('--edge-ip-version', String(settings.edgeIpVersion));
  if (settings.region) args.push('--region', settings.region);
  if (settings.logLevel) args.push('--loglevel', settings.logLevel);
  if (settings.metricsPort) args.push('--metrics', `127.0.0.1:${settings.metricsPort}`);
  args.push('--no-autoupdate');
  // 设置页的「附加参数」以前只写进 config.json，从来没有传给 cloudflared。
  args.push(...splitArgs(settings.extraArgs));
  return args;
}

function yamlScalar(value) {
  const s = String(value == null ? '' : value);
  if (s === '') return '""';
  if (/^[A-Za-z0-9_./:@*+-]+$/.test(s) && !/^(true|false|null|yes|no|on|off|~)$/i.test(s)) return s;
  return JSON.stringify(s);
}

function buildConfigYaml(tunnel, credentialsFile) {
  const lines = [
    '# Generated by Cloudflare Tunnel for fnOS. Manual edits are overwritten.',
  ];
  const tunnelRef = tunnel.tunnelId || tunnel.tunnelName;
  if (tunnelRef) lines.push(`tunnel: ${yamlScalar(tunnelRef)}`);
  if (credentialsFile) lines.push(`credentials-file: ${yamlScalar(credentialsFile)}`);
  lines.push('ingress:');
  for (const rule of tunnel.ingress) {
    if (!rule.hostname) continue;
    lines.push(`  - hostname: ${yamlScalar(rule.hostname)}`);
    if (rule.path) lines.push(`    path: ${yamlScalar(rule.path)}`);
    lines.push(`    service: ${yamlScalar(rule.service || 'http://127.0.0.1:80')}`);
    const origin = {};
    if (rule.noTLSVerify) origin.noTLSVerify = true;
    if (rule.originServerName) origin.originServerName = rule.originServerName;
    if (rule.httpHostHeader) origin.httpHostHeader = rule.httpHostHeader;
    const keys = Object.keys(origin);
    if (keys.length) {
      lines.push('    originRequest:');
      for (const key of keys) lines.push(`      ${key}: ${yamlScalar(origin[key])}`);
    }
  }
  lines.push(`  - service: ${yamlScalar(tunnel.catchAll || 'http_status:404')}`);
  return lines.join('\n') + '\n';
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/* Resolve the credentials file for a locally-managed tunnel.
 *
 * Only *provable* answers are returned: an explicit path, or the file named
 * after the tunnel UUID that `cloudflared tunnel create` wrote. A tunnel known
 * only by name must NOT fall back to "some .json in the directory" -- with two
 * tunnels on the account that silently runs the wrong one, which looks exactly
 * like a healthy tunnel serving the wrong origin. The caller resolves the name
 * to a UUID first (see resolveTunnelIdByName). */
function resolveCredentials(tunnel) {
  if (tunnel.credentialsFile) {
    return fs.existsSync(tunnel.credentialsFile) ? tunnel.credentialsFile : null;
  }
  if (tunnel.tunnelId && UUID_RE.test(tunnel.tunnelId)) {
    const candidate = path.join(CF_DIR, `${tunnel.tunnelId}.json`);
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

/* Map a tunnel name to its UUID through the account tunnel list. Used when the
 * user picked a tunnel by name: recording the UUID lets every later operation
 * locate <uuid>.json exactly instead of guessing. Best effort -- without a
 * login (or without network) the name simply stays unresolved and the caller
 * reports it. */
async function resolveTunnelIdByName(name) {
  if (!name) return '';
  const listed = await accountListTunnels();
  if (!listed.ok) return '';
  const hit = listed.tunnels.find((t) => t.name === name);
  return hit && hit.id ? hit.id : '';
}

/* Write the generated config.yml for a locally-managed tunnel. Shared by
 * buildArgs and applyLocalConfig so the file has a single writer. */
function writeTunnelConfig(tunnel, credentialsFile) {
  const configPath = path.join(TUNNELS_DIR, tunnel.id, 'config.yml');
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, buildConfigYaml(tunnel, credentialsFile), { mode: 0o600 });
  return configPath;
}

/* Build the argv for one tunnel. Returns {args, env, error}. */
function buildArgs(tunnel, settings) {
  const args = globalArgs(settings || {});
  const env = {}; // extra environment for the child process

  if (tunnel.type === 'token') {
    if (!tunnel.token) return { error: '未配置隧道 Token' };
    // Hand the token over through the environment rather than argv: a process
    // command line is world-readable via /proc, so `--token` would expose the
    // credential to every local user. cloudflared honours TUNNEL_TOKEN.
    args.push('tunnel', 'run');
    env.TUNNEL_TOKEN = tunnel.token;
  } else if (tunnel.type === 'quick') {
    if (!tunnel.target) return { error: '未配置本地服务地址' };
    args.push('tunnel', '--url', tunnel.target);
    if (tunnel.quickHostname) args.push('--hostname', tunnel.quickHostname);
  } else if (tunnel.type === 'local') {
    if (!tunnel.tunnelName && !tunnel.tunnelId) return { error: '未选择已创建的隧道' };
    const cred = resolveCredentials(tunnel);
    if (!cred) {
      return {
        error: tunnel.tunnelId
          ? `找不到隧道凭据文件 ${path.join(CF_DIR, `${tunnel.tunnelId}.json`)}，请先在“账户”页重新创建或重新选择该隧道`
          : `无法确定隧道「${tunnel.tunnelName}」的 UUID，请在“账户”页重新选择该隧道（需要已登录账户）`,
      };
    }
    let configPath;
    try {
      configPath = writeTunnelConfig(tunnel, cred);
    } catch (err) {
      return { error: `写入配置文件失败: ${err.message}` };
    }
    args.push('--config', configPath);
    args.push('tunnel', 'run', tunnel.tunnelName || tunnel.tunnelId);
  } else if (tunnel.type === 'config') {
    if (!tunnel.configFile) return { error: '未指定配置文件路径' };
    if (!fs.existsSync(tunnel.configFile)) return { error: `配置文件不存在: ${tunnel.configFile}` };
    args.push('--config', tunnel.configFile);
    args.push('tunnel', 'run');
  } else {
    return { error: `未知的隧道类型: ${tunnel.type}` };
  }

  if (tunnel.extraArgs) args.push(...splitArgs(tunnel.extraArgs));
  return { args, env };
}

/* ------------------------------------------------- locally-managed workflow */

let loginState = { status: 'idle', url: '', error: '', startedAt: null, child: null };

async function accountLoginStart() {
  if (loginState.child) {
    return { ok: true, url: loginState.url, status: loginState.status };
  }
  fs.mkdirSync(CF_DIR, { recursive: true });
  try {
    fs.unlinkSync(CERT_FILE);
  } catch (err) {
    /* no previous cert */
  }
  loginState = { status: 'waiting', url: '', error: '', startedAt: new Date().toISOString(), child: null };

  const child = spawn(CF_BIN, ['tunnel', 'login'], {
    cwd: PKGVAR,
    env: cfEnv(),
    stdio: ['ignore', 'pipe', 'pipe'],
    detached: false,
  });
  loginState.child = child;

  const scan = (buf) => {
    const text = buf.toString('utf8');
    const m = text.match(/https:\/\/[^\s"'<>]+/);
    if (m && !loginState.url) {
      loginState.url = m[0].replace(/[.,)]+$/, '');
      logInfo('cloudflared login URL captured');
    }
  };
  child.stdout.on('data', scan);
  child.stderr.on('data', scan);

  child.on('error', (err) => {
    loginState.status = 'error';
    loginState.error = err.message;
    loginState.child = null;
  });
  child.on('exit', (code) => {
    loginState.child = null;
    if (fs.existsSync(CERT_FILE)) {
      loginState.status = 'done';
      loginState.error = '';
    } else if (loginState.status !== 'error') {
      // 退出码 0 是用户没完成授权就关掉了页面，不是失败；非 0 才是真的出错。
      loginState.status = 'error';
      loginState.error =
        loginState.error ||
        (code === 0 ? '登录已取消，未获取到 cert.pem' : `登录进程退出（退出码 ${code}），未获取到 cert.pem`);
    }
  });

  /* cert.pem appearing is the authoritative success signal */
  const poll = setInterval(() => {
    if (fs.existsSync(CERT_FILE)) {
      loginState.status = 'done';
      loginState.error = '';
      if (loginState.child) {
        try {
          loginState.child.kill('SIGTERM');
        } catch (err) {
          /* ignore */
        }
      }
      clearInterval(poll);
    } else if (!loginState.child && loginState.status !== 'done') {
      clearInterval(poll);
    }
  }, 1000);
  poll.unref();

  return { ok: true, url: '', status: loginState.status };
}

function accountLoginStatus() {
  const loggedIn = fs.existsSync(CERT_FILE);
  return {
    loggedIn,
    status: loggedIn ? 'done' : loginState.status,
    url: loginState.url,
    error: loginState.error,
    startedAt: loginState.startedAt,
    certPath: CERT_FILE,
  };
}

function accountLogout() {
  if (loginState.child) {
    try {
      loginState.child.kill('SIGTERM');
    } catch (err) {
      /* ignore */
    }
  }
  loginState = { status: 'idle', url: '', error: '', startedAt: null, child: null };
  try {
    fs.unlinkSync(CERT_FILE);
  } catch (err) {
    /* already gone */
  }
  return { ok: true };
}

function parseJsonOutput(text) {
  const start = text.indexOf('[');
  const startObj = text.indexOf('{');
  let idx = -1;
  if (start >= 0 && (startObj < 0 || start < startObj)) idx = start;
  else idx = startObj;
  if (idx < 0) return null;
  try {
    return JSON.parse(text.slice(idx));
  } catch (err) {
    return null;
  }
}

async function accountListTunnels() {
  if (!fs.existsSync(CERT_FILE)) return { ok: false, error: '尚未登录 Cloudflare 账户', tunnels: [] };
  /* `--output` is a *subcommand* flag in cloudflared's CLI, so it has to follow
   * `list`; before the subcommand it is rejected as an unknown tunnel option. */
  const res = await cfExec(['tunnel', 'list', '--output', 'json'], { timeout: 30000 });
  if (res.code !== 0) {
    const msg = (res.stderr || res.stdout || res.error || '').trim().split('\n').slice(-3).join(' ');
    return { ok: false, error: msg || `cloudflared 退出码 ${res.code}`, tunnels: [] };
  }
  const parsed = parseJsonOutput(res.stdout);
  const list = Array.isArray(parsed) ? parsed : (parsed && parsed.tunnels) || [];
  return {
    ok: true,
    tunnels: list.map((t) => ({
      id: t.id || '',
      name: t.name || '',
      createdAt: t.createdAt || t.created_at || '',
      connections: Array.isArray(t.connections) ? t.connections.length : 0,
    })),
  };
}

async function accountCreateTunnel(name) {
  if (!fs.existsSync(CERT_FILE)) return { ok: false, error: '尚未登录 Cloudflare 账户' };
  if (!/^[A-Za-z0-9._-]{1,64}$/.test(String(name || ''))) {
    return { ok: false, error: '隧道名称只能包含字母、数字、点、下划线和连字符' };
  }
  const res = await cfExec(['tunnel', 'create', '--output', 'json', name], { timeout: 60000 });
  const combined = (res.stdout + '\n' + res.stderr).trim();
  if (res.code !== 0) {
    return { ok: false, error: combined.split('\n').slice(-3).join(' ') || `退出码 ${res.code}` };
  }
  const parsed = parseJsonOutput(res.stdout);
  return { ok: true, tunnel: parsed || null, output: combined };
}

async function accountDeleteTunnel(name) {
  if (!fs.existsSync(CERT_FILE)) return { ok: false, error: '尚未登录 Cloudflare 账户' };
  if (!/^[A-Za-z0-9._-]{1,64}$/.test(String(name || ''))) {
    return { ok: false, error: '非法的隧道名称' };
  }
  const res = await cfExec(['tunnel', 'delete', '-f', name], { timeout: 60000 });
  if (res.code !== 0) {
    return { ok: false, error: ((res.stderr || res.stdout) || '').trim().split('\n').slice(-3).join(' ') };
  }
  return { ok: true };
}

async function accountRouteDns(name, hostname) {
  if (!fs.existsSync(CERT_FILE)) return { ok: false, error: '尚未登录 Cloudflare 账户' };
  if (!/^[A-Za-z0-9._-]{1,64}$/.test(String(name || ''))) return { ok: false, error: '非法的隧道名称' };
  if (!/^(\*\.)?([A-Za-z0-9_-]+\.)+[A-Za-z]{2,}$/.test(String(hostname || ''))) {
    return { ok: false, error: '非法的域名' };
  }
  const res = await cfExec(['tunnel', 'route', 'dns', '--overwrite-dns', name, hostname], { timeout: 60000 });
  if (res.code !== 0) {
    return { ok: false, error: ((res.stderr || res.stdout) || '').trim().split('\n').slice(-3).join(' ') };
  }
  return { ok: true, output: (res.stdout + res.stderr).trim() };
}

function readAppVersion() {
  try {
    const manifest = fs.readFileSync(path.join(APPDEST, '..', 'manifest'), 'utf8');
    const m = manifest.match(/^version\s*=\s*(.+)$/m);
    return m ? m[1].trim() : '';
  } catch (err) {
    return '';
  }
}

/* Replace the bundled cloudflared with the newest upstream release. The binary
 * lives in the app payload, so an app upgrade overwrites it again; the version
 * actually in use is recorded in the var directory. */
async function updateBinary() {
  const archMap = { x64: 'amd64', arm64: 'arm64' };
  const arch = archMap[process.arch];
  if (!arch) return { ok: false, error: `不支持的架构: ${process.arch}` };
  const api = 'https://api.github.com/repos/cloudflare/cloudflared/releases/latest';
  const https = require('https');
  const fetchJson = (url) =>
    new Promise((resolve, reject) => {
      https
        .get(url, { headers: { 'User-Agent': 'fnos-cloudflared' } }, (r) => {
          if (r.statusCode >= 300 && r.statusCode < 400 && r.headers.location) {
            r.resume();
            return resolve(fetchJson(r.headers.location));
          }
          let data = '';
          r.on('data', (c) => (data += c));
          r.on('end', () => {
            try {
              resolve(JSON.parse(data));
            } catch (err) {
              reject(new Error('无法解析 GitHub 响应'));
            }
          });
        })
        .on('error', reject);
    });

  try {
    const release = await fetchJson(api);
    const asset = (release.assets || []).find((a) => a.name === `cloudflared-linux-${arch}`);
    if (!asset) return { ok: false, error: `未找到适配 ${arch} 的发布文件` };
    const tmp = path.join(PKGTMP, `cloudflared-${Date.now()}`);
    await new Promise((resolve, reject) => {
      const file = fs.createWriteStream(tmp);
      const get = (url) =>
        https.get(url, { headers: { 'User-Agent': 'fnos-cloudflared' } }, (r) => {
          if (r.statusCode >= 300 && r.statusCode < 400 && r.headers.location) {
            r.resume();
            return get(r.headers.location);
          }
          r.pipe(file);
          file.on('finish', () => file.close(resolve));
        });
      get(asset.browser_download_url).on('error', reject);
    });
    fs.chmodSync(tmp, 0o755);
    atomicWrite(CF_BIN, fs.readFileSync(tmp), 0o755);
    fs.unlinkSync(tmp);
    const version = await cloudflaredVersion(true);
    atomicWrite(CF_VERSION_FILE, `${version}\n`, 0o644);
    logInfo(`cloudflared binary updated to ${version}`);
    return { ok: true, version };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

module.exports = {
  cfEnv,
  cfExec,
  cloudflaredVersion,
  splitArgs,
  globalArgs,
  buildConfigYaml,
  buildArgs,
  resolveCredentials,
  resolveTunnelIdByName,
  UUID_RE,
  writeTunnelConfig,
  accountLoginStart,
  accountLoginStatus,
  accountLogout,
  accountListTunnels,
  accountCreateTunnel,
  accountDeleteTunnel,
  accountRouteDns,
  readAppVersion,
  updateBinary,
};
